name: benheath
favicon: null
layout_spectrum: 0.08680533058941364
typography_spectrum: 0.11718027736060321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6393963561858982
  lightness: 0.21659229253418744
  saturation: 0.1719481477048248
  rhythmicContrast: 0.0663089226000011
purpose: []
